version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2022
clone_depth: 1
build_script:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop;

    Microsoft.PowerShell.Core\Set-StrictMode -Version 1;

    $ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue;


    # Reason: AppVeyor build image 'Visual Studio 2022' doesn't contain .NET 5.0 SDK anymore

    choco install --yes --no-progress 'dotnet-5.0-sdk-4xx';


    # # Install R language to use for `RPlotExporter`
    #
    # choco install --yes --no-progress r;


    Compress-Archive -Force -CompressionLevel Optimal -DestinationPath 'Sources.zip' -Path '*';


    & ./run.ps1 -AppveyorBuild;


    Compress-Archive -Force -CompressionLevel Optimal -DestinationPath '.out/Binaries.zip' -Path '.out/bin/*';


    Compress-Archive -Force -CompressionLevel Optimal -DestinationPath '.out/TestResults.zip' -Path '.out/TestResults/*';


    Compress-Archive -Force -CompressionLevel Optimal -DestinationPath '.out/Benchmarks.zip' -Path '.out/Benchmarks/*';
test: off
artifacts:
- path: Sources.zip
  name: Sources
- path: .out/Binaries.zip
  name: Binaries
- path: .out/TestResults.zip
  name: TestResults
- path: .out/Benchmarks.zip
  name: Benchmarks
notifications:
- provider: Email
  to:
  - vitalii.maklai@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
